### ISSUE TITLE
UICollectionView is not working.

### ISSUE THREAD

**Issue by panatlanticdev** [suzuki-0000/SKPhotoBrowser#1]
I used this library but when I click on an image from the collectionView it does not show the correct image. 

and im using the same images as the example. 

import UIKit
import SKPhotoBrowser

class PhotoThumbsVC: UIViewController, UICollectionViewDelegate, UICollectionViewDataSource, SKPhotoBrowserDelegate {

    @IBOutlet var collectionView: UICollectionView!
    
    var images = [SKPhoto]()
    
    var caption = ["Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        "It has survived not on/Users/a12556/workspace/_origin/SKPhotoBrowser/README.mdly five centuries, but also the leap into electronic typesetting",
        "remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        "It has survived not only five centuries, but also the leap into electronic typesetting",
        "remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        "It has survived not only five centuries, but also the leap into electronic typesetting",
        "remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."]
    
    
    override func viewDidLoad() {
        super.viewDidLoad()

        for i in 0..<30{
            let photo = SKPhoto.photoWithImage(UIImage(named: "image\(i%10).jpg")!)
            photo.caption = caption[i%10]
            images.append(photo)
        }
        setupCollectionView()
        // Do any additional setup after loading the view.
    }
    
    private func setupCollectionView (){
        collectionView.delegate = self
        collectionView.dataSource = self
    }

     // MARK: - UICollectionViewDataSource
    
    func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return images.count
    } 

    func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCellWithReuseIdentifier("imageCell", forIndexPath: indexPath) as! CustomThumbsCell
        
        cell.fotoThumb.image = images[indexPath.row].underlyingImage
        
        return cell
    }
    
    
    
    // MARK: - UICollectionViewDelegate
    
    func collectionView(collectionView: UICollectionView, didDeselectItemAtIndexPath indexPath: NSIndexPath) {
        let cell = collectionView.cellForItemAtIndexPath(indexPath) as! CustomThumbsCell
        let originImage = cell.fotoThumb.image!
        let browser = SKPhotoBrowser(originImage: originImage, photos: images, animatedFromView: cell)
        browser.initializePageIndex(indexPath.row)
        browser.delegate = self
        presentViewController(browser, animated: true, completion: {})
    }
    
    
    
    // MARK: - SKPhotoBrowserDelegate
    func didShowPhotoAtIndex(index: Int) {
        // do some handle if you need
    }
    
    func willDismissAtPageIndex(index: Int) {
        // do some handle if you need
    }
    
    func didDismissAtPageIndex(index: Int) {
        // do some handle if you need
    }
    
  

}

class CustomThumbsCell: UICollectionViewCell {
    
    @IBOutlet weak var fotoThumb: UIImageView!
    
    
    override func awakeFromNib() {
        super.awakeFromNib()
        fotoThumb.image = nil
    }
    
    override func prepareForReuse() {
        fotoThumb.image = nil
    }
}

**Comment by suzuki-0000** [comment]
I'm not exactly understand what is "not show the correct image."
which means image showed but not correct size? or image did not show?

**Comment by thebertozz** [comment]
Hi! I'm trying to use your framework loading images from URLs, but there's one problem: when you use images from Urls, the cells for the collection view are always black, and if you click them you get "fatal error: unexpectedly found nil while unwrapping an Optional value" on this line of code: `let originImage = cell.exampleImageView.image!`. The workaround is to leave at least one of the asset images and then tap on its cell to go to the slider, then you see that the images are loaded correctly. Basically the cell for the images loaded from urls are always nil for me; how can i solve that? I've uploaded a video to better explain the problem: 
https://onedrive.live.com/redir?resid=F7658DD1EE060819!31633&authkey=!AMNetjCGijyLpzM&ithint=file%2cmov
Thanks for the great work!

**Comment by suzuki-0000** [comment]
hi, @thebertozz 
I'm afraid but if you want to show in your collection/table cell in your image from web url, you have to write it yourself. you can only use SKPhotoBrowser for PhotoBrowsing but not for collection/tableView's layout or cell.

I think you can write like following,
```
 func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCellWithReuseIdentifier("exampleCollectionViewCell", forIndexPath: indexPath) as! ExampleCollectionViewCell

        // image URL 
        let urlStringComesFromWeb = "https://placehold.jp/150x15\(indexPath.row).png"	

        // add
        let photo = SKPhoto.photoWithImageURL(urlStringComesFromWeb)
        images.append(photo)		

        // set from URL in you cell
        cell.setExampleImageViewFromURL(urlStringComesFromWeb)
        
        return cell
    }


class ExampleCollectionViewCell:UICollectionViewCell{
    
    @IBOutlet weak var exampleImageView: UIImageView!
    
    override func awakeFromNib() {
        super.awakeFromNib()
        exampleImageView.image = nil
    }
    
    override func prepareForReuse() {
        exampleImageView.image = nil
    }
	
	func setExampleImageViewFromURL(url: String){
		// Fetch Image
		let session = NSURLSession(configuration: NSURLSessionConfiguration.defaultSessionConfiguration())
		if let nsURL = NSURL(string: url) {
			session.dataTaskWithURL(nsURL, completionHandler: {
				(response: NSData?, data: NSURLResponse?, error: NSError?) in
				if error != nil {
					dispatch_async(dispatch_get_main_queue()) {
						self.exampleImageView.image = UIImage()
					}
				}
				if let res = response, let image = UIImage(data: res) {
					dispatch_async(dispatch_get_main_queue()) {
						self.exampleImageView.image = image
					}
				}
				session.finishTasksAndInvalidate()
			}).resume()
		}
		return 
	}
}


```

`setExampleImageViewFromURL` is not good implement, i think you should use [KingFisher](https://github.com/onevcat/Kingfisher) or something.

I think readme is misreadable, so i should rewrite it anyway.

**Comment by tiangaodihoushiwo** [comment]
hi when i use import SKPhotoBrowser,there's one problem:No such module 'SKPhotoBrowser'  i checked the file  and find there is no SKPhotoBrowser.framework.  thank you ~
