### ISSUE TITLE
fatal error: array cannot be bridged from Objective-C

### ISSUE THREAD

**Issue by gustavogervasio** [suzuki-0000/SKPhotoBrowser#104]
var images = [SKPhoto]()
            for image in prod.getImages() {
                let photo = SKPhoto.photoWithImageURL(image.fullHdUrl)
                images.append(photo)
            }
            // create PhotoBrowser Instance, and present.
            let browser = SKPhotoBrowser(photos: images)

fatal error: array cannot be bridged from Objective-C
Printing description of browser:
expression produced error: /var/folders/m9/t1ngjfsx4x9fftc2s2_xtt400000gn/T/lldb/62798/expr8.swift:1:46: error: use of undeclared type 'SKPhotoBrowser'
$__lldb__DumpForDebugger(Swift.UnsafePointer<SKPhotoBrowser.SKPhotoBrowser>(bitPattern: 0x134573ac0).memory)
                                             ^~~~~~~~~~~~~~
/var/folders/m9/t1ngjfsx4x9fftc2s2_xtt400000gn/T/lldb/62798/expr8.swift:1:45: note: while parsing this '<' as a type parameter bracket
$__lldb__DumpForDebugger(Swift.UnsafePointer<SKPhotoBrowser.SKPhotoBrowser>(bitPattern: 0x134573ac0).memory)

**Comment by krummler** [comment]
Did you try master? This seems to be the issue fixed in #102

**Comment by gustavogervasio** [comment]
I was getting the release 1.8.8 version. Now a get the master and it is resolved.

Thanks 👍
