### ISSUE TITLE
Fatal Error: Array cannot be bridged from Objective-C

### ISSUE THREAD

**Issue by hjaurum** [suzuki-0000/SKPhotoBrowser#105]
I used 1.8.6 , it works fine.
But since I updated to the new version （1.8.8）, an error occurred
`var skPhotos = [SKPhoto]()`
            `let photoDatas = self.item.photos`
            `do{`
                `for photoData in photoDatas{`
                   `let data = try photoData.getData()`
                   `skPhotos.append(SKPhoto.photoWithImage(UIImage(data: data)!))`
               `}`
           `}catch{`
           `}`
           `let skPhotoBrowser = SKPhotoBrowser(photos: skPhotos)//Throw that error! Fatal Error: Array cannot be bridged from Objective-C`

**Comment by barrault01** [comment]
The master is up to date and fixed this issue but it need to publish a new pod.

**Comment by suzuki-0000** [comment]
@hjaurum now I'm updating pod to 1.8.9.  so you can use this pod version.

**Comment by qiuncheng** [comment]
I also occasionally met this problem today,  but didn't find v1.8.9 now?

**Comment by suzuki-0000** [comment]
@qiuncheng what kind of version did you use? could you try v1.8.9 or later version?

**Comment by qiuncheng** [comment]
was using v1.8.8 ever，but now using v1.8.6，don't meet this error again！ @suzuki-0000

**Comment by leancmscn** [comment]
same problem!!!

```
        let browser = SKPhotoBrowser(photos: skPhotos)
```

**Comment by suzuki-0000** [comment]
no sure why this issue is happen, i fixed this problem at v.1.8.8 and don't meet this problem ever.

**Comment by suzuki-0000** [comment]
please reopen when v4.0.0 will happen this trouble
