### ISSUE TITLE
Glitch when origin imageview is not correct size

### ISSUE THREAD

**Issue by RSully** [suzuki-0000/SKPhotoBrowser#108]
I have a UICollectionViewController subclass where each cell is a UIImageView (similar to your example project). However, my image view's `contentMode` is set to `ScaleAspectFit` (because my images may have different sizes). Thus, my sender frame is not the same as my image view's frame.

When I dismiss the `SKPhotoBrowser` view controller the animation is incorrect, it scales the image to the view's frame, stretching the image, before disappearing.

**Comment by suzuki-0000** [comment]
I updated this issue in v3.0.x. 
try `contentMode` SKPhoto property. I wrote example at SKPhotoBrowserExample.

Please create new issue if it still have problem.
