### ISSUE TITLE
Objective-c version

### ISSUE THREAD

**Issue by darkelfrullez** [suzuki-0000/SKPhotoBrowser#11]
Do you have obj-c version of this lib or may have some plans to make it? Its exactly what i want but its on swift :(

**Comment by suzuki-0000** [comment]
hi @darkelfrullez 
this source based on IDMPhotoBrowser, MWPhotoBrowser, which is wrote by obj-c. I think you prefer to use of those.

**Comment by darkelfrullez** [comment]
Yeah, i know, but you miss "exactly" ;) anyway thanks for your browser :)

**Comment by pj4533** [comment]
@darkelfrullez well to be fair,  IDMPhotoBrowser has _more_ functionality than SKPhotoBrowser (right now at least).  So if you want Objective-C, IDMPhotoBrowser is the way to go.  Take at the look at the code, the architecture is the same.
