### ISSUE TITLE
Custom Cache and ImageDownloader + Floating View

### ISSUE THREAD

**Issue by iAlirezaKML** [suzuki-0000/SKPhotoBrowser#110]
How can I use a custom cache and downloader? I use **Kingfisher** as my MainImageManager, so when loading a new image from url, both **SKPhotoBrowser** and **Kingfisher** downloading the photo.

P.S:
I had one other problem: I have a floating view (like FAB button), when dismissing a photo by swipe, it's animation covers the floating view till it's fit in the source rect. How can I manage this? (I've tried to send the animating view to back of the floating view, but in another view I have two floating buttons that this workaround won't work.)

Also when a photo is dismissed by swipe where source rect is not in view, the animation is weird (flickering till disappears), I've managed it by manipulating the `SKPhotoBrowser` class, but I just wanted to know do you have any straight solution for that?

Thanks! 😊

**Comment by kevinwo** [comment]
+1 for custom cache configuration. I'm going to try to work on a fork later today or tomorrow.

**Comment by kevinwo** [comment]
Hi @peymayesh. I've submitted a pull request with my custom cache solution.  In the mean time, if you're interested in testing, you can play with it on my fork:

https://github.com/kevinwo/SKPhotoBrowser

**Comment by kevinwo** [comment]
@peymayesh @suzuki-0000 has merged my pull request, so you should be able to use a custom cache now.

**Comment by madsb** [comment]
Sounds great, @kevinwo! How would you go about using a custom cache manager such as Kingfisher using your code?

**Comment by peymayesh** [comment]
@kevinwo Thanks! Did great! 👍
