### ISSUE TITLE
There is an issue while rotating the phone

### ISSUE THREAD

**Issue by AjayDhanju** [suzuki-0000/SKPhotoBrowser#114]
when rotate to landscape from portrait  or vise versa, Image zoom to max than rest to minimum zoom.
![img_0020](https://cloud.githubusercontent.com/assets/14290073/16512379/515b298a-3f78-11e6-95b5-ed2ee425643f.PNG)
![img_0023](https://cloud.githubusercontent.com/assets/14290073/16512380/531c5b86-3f78-11e6-88c7-0f7bc3c4fcf4.PNG)
![img_0022](https://cloud.githubusercontent.com/assets/14290073/16512383/54a4b552-3f78-11e6-9d3f-ab5d70acdd7e.PNG)

**Comment by suzuki-0000** [comment]
swift4.0 may not happen so that this may be able to be closed. 
please re-open when new issue arise.
