### ISSUE TITLE
how to disable the 

### ISSUE THREAD

**Issue by l12ab** [suzuki-0000/SKPhotoBrowser#115]
by default, single tap or swipe will let status bar, toolbar and close button disappear.
but if enable single tap dismiss, and use navigationcontroller, when the status bar, toolbar and close button are disappeared, and tap the screen, it will show a statusbar & navigationbar 's height transition, it's ugly.

so i think if single tap dismiss is enabled, dont hide the status bar, toolbar and close button when singtap or swipe

**Comment by suzuki-0000** [comment]
i remove statusbar implement because it can handle from delegate. so this problem will fixed at v3.0.x. 
please create new issue if it has new problem.
