### ISSUE TITLE
Problem margin 

### ISSUE THREAD

**Issue by erolando** [suzuki-0000/SKPhotoBrowser#119]
i have a next problem

ignores the gray boxes

error #1 

![screen shot 2016-08-03 at 5 47 22 pm](https://cloud.githubusercontent.com/assets/1770136/17384550/94d3d628-59a2-11e6-99c2-a5cc27ce82e5.png)

**Comment by erolando** [comment]
and second error, not compile

![screen shot 2016-08-09 at 9 26 32 am](https://cloud.githubusercontent.com/assets/1770136/17519923/84dc5f4a-5e13-11e6-956f-b91982b3a716.png)

**Comment by erolando** [comment]
i change next code:

`override public func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        isPerformingLayout = true
        pagingScrollView.frame = frameForPagingScrollView()
        pagingScrollView.contentSize = contentSizeForPagingScrollView()        
        // resize frames of buttons after the device rotation
        //frameForButton()
        
        // this algorithm resizes the current image after device rotation
        if visiblePages.count > 0 {
            for page in visiblePages {
                let pageIndex = page.tag - pageIndexTagOffset
                page.frame = frameForPageAtIndex(pageIndex)
                page.setMaxMinZoomScalesForCurrentBounds()
                if page.captionView != nil {
                    page.captionView.frame = frameForCaptionView(page.captionView, index: pageIndex)
                }
            }
        }
       // this contents offset cause error #1 
        if isRotation {
            pagingScrollView.contentOffset = contentOffsetForPageAtIndex(currentPageIndex)
            self.isRotation = false
        }
        // where did start
        didStartViewingPageAtIndex(currentPageIndex)
        
        toolBar.frame = frameForToolbarAtOrientation()
        isPerformingLayout = false
    }
    //add support with multitasking 
    override public func viewWillTransitionToSize(size: CGSize, withTransitionCoordinator coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransitionToSize(size, withTransitionCoordinator: coordinator)
        coordinator.animateAlongsideTransition({ (context) -> Void in
                UIView.animateWithDuration(0.3, animations: { () -> Void in
                    self.view.frame = CGRectMake(0, 0, size.width, size.height);
                    self.isRotation = true
                    self.reloadData()
                })
            }, completion: { (context) -> Void in
        })
    }`

**Comment by suzuki-0000** [comment]
I think this problem has fixed already. please reopen when v4.0.0 will happen this trouble.
