### ISSUE TITLE
Can i show Video on this Browser?

### ISSUE THREAD

**Issue by TheEngineerz** [suzuki-0000/SKPhotoBrowser#122]

**Comment by ankit-betterbutter** [comment]
did you solve this by any means?

**Comment by TheEngineerz** [comment]
I am using this library for my project

https://github.com/mwaterfall/MWPhotoBrowser It gives the support for both

**Comment by ankit-betterbutter** [comment]
Thanks mate. Will let you know if I have any issues.

**Comment by Tweak1981** [comment]
i love the SKPhotoBrowser... please add Video-support ;-)

**Comment by MohamedElzokla** [comment]
@Tweak1981 
check this fork for video support
https://github.com/MohamedElzokla/SKPhotoBrowser.git

**Comment by Liyongcong** [comment]
> @Tweak1981 check this fork for video support https://github.com/MohamedElzokla/SKPhotoBrowser.git
I downloaded it and tried it, but the video didn't load up and play
