### ISSUE TITLE
How to using custom cache instead of default cache

### ISSUE THREAD

**Issue by morpheus1984** [suzuki-0000/SKPhotoBrowser#124]
I use SDWebImage SDK For manager Image download,show,cache and I want to using it in SKPhotoBrowser。but how to do？

**Comment by morpheus1984** [comment]
I use SDWebImage SDK For manager Image download,show,cache and I want to using it in SKPhotoBrowser。but how to do？

**Comment by suzuki-0000** [comment]
I wrote some example at SKPhotoBrowserExample and README.md. 
please check it
