### ISSUE TITLE
GIF Support

### ISSUE THREAD

**Issue by Kalvin126** [suzuki-0000/SKPhotoBrowser#129]
Is there any plans to support GIFs?

**Comment by Luccifer** [comment]
You can make your own extension for UIImage and adopt UIImage for SKPhoto, what the problem?
SKPhoto.photoWithImage(UIImage.gifWithData(NSData(

**Comment by Kalvin126** [comment]
gifWithData must be another extension? I've found a working framework to do this. Didn't know it was that simple aha.
