### ISSUE TITLE
UIActionSheet & UIPopoverController deprecated

### ISSUE THREAD

**Issue by pj4533** [suzuki-0000/SKPhotoBrowser#13]
I ported over the action button functionality from IDMPhotoBrowser, but didn't realize they were using deprecated code.   I'll update & submit a pull request to get rid of the warnings.

**Comment by suzuki-0000** [comment]
:+1:

**Comment by alexsanderskywork** [comment]
@pj4533 I fixed it.

**Comment by alexsanderskywork** [comment]
@suzuki-0000 you can close this because I made it in previous pull request
