### ISSUE TITLE
Swift3.0

### ISSUE THREAD

**Issue by suzuki-0000** [suzuki-0000/SKPhotoBrowser#131]

**Comment by Luccifer** [comment]
any rumours?

**Comment by Jirmi** [comment]
I am also wondering if there will be swift 3 update please.

**Comment by madsb** [comment]
Just created a pull request with a Swift 3 conversion: #142

**Comment by suzuki-0000** [comment]
@madsb thanks your pull request. I create [swift3 branch](https://github.com/suzuki-0000/SKPhotoBrowser/tree/swift3) for it, so can you re-make your pull request to that?

**Comment by madsb** [comment]
@suzuki-0000 Done!

**Comment by suzuki-0000** [comment]
thanks @madsb!  [swift3 branch is here.](https://github.com/suzuki-0000/SKPhotoBrowser/tree/swift3) 
when it should merge to master is the next consideration but not now.
