### ISSUE TITLE
Make it work with data Url

### ISSUE THREAD

**Issue by hainguyen86** [suzuki-0000/SKPhotoBrowser#132]
Can you make SKPhotoBrowser download url from url that don't have file.extension
sample: mobile/ajax.php?attachedId=54&action=show&ncc=1&cache_image=Y&mobile_action=disk_uf_view&width=1300&height=1300&signature=cde859e9b48405ec7f81f7b709639f6ed41bd368b576746ddfd76c5179729fdf

Thanks,

**Comment by suzuki-0000** [comment]
Not sure what you're exactly say. inside this source uses `NSURLSession` when fetch from url, so It might do if NSURLSession can do

**Comment by hainguyen86** [comment]
Thanks @suzuki-0000 for your supporting,
I have a problem when I pass that url to safari on Mac the image is displayed but SKPhotoBrowser show nothing.
I will try another way :)
