### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by ibeleliev** [suzuki-0000/SKPhotoBrowser#133]
Hello. 
With the newest version of SKPhotoBrowser ( 3.0.0 ) i am getting this fatal error when the browser loads and displays one of the pictures. It is marking this line from the code
`guard let page = self.pagingScrollView.pageDisplayingAtPhoto(photo), let photo = page.photo else {`
and using the debugger to get some information it shows that
`(lldb) p pagingScrollView
(SKPhotoBrowser.SKPagingScrollView!) $R1 = nil`
and 
`(lldb) po pagingScrollView
fatal error: unexpectedly found nil while unwrapping an Optional value
expression produced error: /var/folders/gv/hmkzdb493jbcg1drw2m_6h_80000gn/T/lldb/410/expr127.swift:1:95: error: 'SKPagingScrollView' is not a member type of '$__lldb_context' (aka 'SKPhotoBrowser')
$__lldb__DumpForDebugger(Swift.UnsafePointer<Swift.ImplicitlyUnwrappedOptional<SKPhotoBrowser.SKPagingScrollView>>(bitPattern: 0x11f483eb0).memory)
                                                                               ~~~~~~~~~~~~~~ ^
/var/folders/gv/hmkzdb493jbcg1drw2m_6h_80000gn/T/lldb/410/expr127.swift:1:45: note: while parsing this '<' as a type parameter bracket
$__lldb__DumpForDebugger(Swift.UnsafePointer<Swift.ImplicitlyUnwrappedOptional<SKPhotoBrowser.SKPagingScrollView>>(bitPattern: 0x11f483eb0).memory)`
And now im using version 2.0.3 since i don't have that problem there.

**Comment by suzuki-0000** [comment]
hi, I will check it. what is your initializer?  e.g. `SKPhotoBrowser(photos: images)` or `SKPhotoBrowser(originImage:, photos: x, animatedFromView:) `

**Comment by ibeleliev** [comment]
I am using the second one:
`SKPhotoBrowser(originImage: <#T##UIImage#>, photos: <#T##[SKPhotoProtocol]#>, animatedFromView: <#T##UIView#>)`

**Comment by suzuki-0000** [comment]
I tried debug using example project but did not happen. do you think you can find what is the defference between your project and exapmle project?

**Comment by suzuki-0000** [comment]
I silll not found why this case cause, but please try v3.0.2. property goes lazy so this error might not happen

**Comment by ibeleliev** [comment]
Hi i just saw your replies.
Well in version 3.0.2 i no longer have the issue i had in 3.0.
And the only thing different in my code is that i am using your library for a xib file in descendant of UIView not a controller and the way i was presenting the browser was using a "weak var presenter: UIViewController?" that links the xib with the view controller. Anyway this issue should be closed now :) Good job on the kawaii library btw :)
