### ISSUE TITLE
Impossible to zoom when resolution is 1024x768

### ISSUE THREAD

**Issue by nicol3a** [suzuki-0000/SKPhotoBrowser#134]
The method `setMaxMinZoomScalesForCurrentBounds` in `SKZoomingScrollView` has a problem when the resolution of the screen is 1024x768px (iPad non-Retina).

The algorithm sets the `minimumZoomScale` and the `maximumZoomScale` to the same value, which result in no zoom possible.

Could you update this method to make it work?

**Comment by suzuki-0000** [comment]
well I will try it.

**Comment by suzuki-0000** [comment]
please confirm v3.0.2,  this issue might be fixed

**Comment by nicol3a** [comment]
It's fixed. Thanks a lot!
