### ISSUE TITLE
Crash after dismissing share mail extension

### ISSUE THREAD

**Issue by fenomenar9** [suzuki-0000/SKPhotoBrowser#14]
After tapping the share button and selecting the mail or sms share extensions, the app systematically crashes when dismissing the view controller

**Comment by fenomenar9** [comment]
I figured the issue. when the mail share extension is dismissed viewWillAppear gets called in skPhotoBrowser calling reloadData() which caused the bug.
I moved reloadData() to viewDidLoad() method and it 's working fine now

**Comment by suzuki-0000** [comment]
@fenomenar9 thanks your issue, and confirm bugs.
I confirmed and I found that problem is pagingScrollView will nil when viewDidDisappear called.
I tried to test and will fix this bug.

**Comment by suzuki-0000** [comment]
@fenomenar9  I fixed it at [here](https://github.com/suzuki-0000/SKPhotoBrowser/pull/15). thanks!

**Comment by fenomenar9** [comment]
Thank you very much :+1:
