### ISSUE TITLE
not support swift 3

### ISSUE THREAD

**Issue by sonysum** [suzuki-0000/SKPhotoBrowser#147]

**Comment by rodrigoruiz** [comment]
Any update on this?

**Comment by madsb** [comment]
The Swift 3 branch is here: https://github.com/suzuki-0000/SKPhotoBrowser/tree/swift3

**Comment by SwiftRabbit** [comment]
At this time : pod 'SKPhotoBrowser', :git => 'https://github.com/suzuki-0000/SKPhotoBrowser.git', :branch => 'swift3'

**Comment by suzuki-0000** [comment]
I may should wrote at readme how to use swift3.x. I will.
