### ISSUE TITLE
First entered displayAction is showed

### ISSUE THREAD

**Issue by huangboju** [suzuki-0000/SKPhotoBrowser#149]
SKPhotoBrowserOptions.displayAction = false,
but first entered displayAction is showed

**Comment by suzuki-0000** [comment]
I'm not sure what `First entered` mean. 
I checked displayAction option and it goes well both false and true.

`SKPhotoBrowserOptions.displayAction = false`
 
![2016-09-23 13 06 53](https://cloud.githubusercontent.com/assets/1096585/18773946/085360e6-818f-11e6-97cd-a99341b3c44f.png)

---
`SKPhotoBrowserOptions.displayAction = true`

![2016-09-23 13 07 18](https://cloud.githubusercontent.com/assets/1096585/18773945/0853ab64-818f-11e6-951d-5a5ad3669ce3.png)

**Comment by huangboju** [comment]
This is first enter
<img width="1280" alt="2016-09-23 2 06 47" src="https://cloud.githubusercontent.com/assets/14818224/18775873/9d54e2ac-8197-11e6-9c77-1776e030cf38.png">

second enter
<img width="1280" alt="2016-09-23 2 06 58" src="https://cloud.githubusercontent.com/assets/14818224/18775905/c5de6626-8197-11e6-94c5-2598aa671ce0.png">

**Comment by huangboju** [comment]
<img width="569" alt="2016-09-23 2 22 56" src="https://cloud.githubusercontent.com/assets/14818224/18776078/4c0f038a-8199-11e6-9c2c-2a9ef70d79c4.png">
I solved

**Comment by suzuki-0000** [comment]
I see, this option must specified before initialize.(viewDidLoad). so this issue will close.
