### ISSUE TITLE
No custom toolbar in Swift 3 version?

### ISSUE THREAD

**Issue by DesmondPang** [suzuki-0000/SKPhotoBrowser#151]
I cannot change the font of text and button style of the toolbar. No such variables in SKPhotoBrowserOptions

**Comment by suzuki-0000** [comment]
I need to merge it.
But now I straggled with cocoapod for xcode8.(something bad with mine, or some bugs there)
I will try this after it.

**Comment by VictoRD11** [comment]
I'm waiting

**Comment by suzuki-0000** [comment]
hi @DesmondPang  @VictoRD11  now I merged to branch: swift3.
