### ISSUE TITLE
Extract url (string) from photoWithImageURL

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [suzuki-0000/SKPhotoBrowser#153]
I am using `SDWebImage` for loading, cacheing webimages.

The problem is, I have to maintain two different arrays. One for `var imageURLs = [SKPhotoProtocol]()`  & other for `var arrImageURLs = [String]()`  in order to load & cache image using `SDWebImage`.

Now, `cellForItemAt` method `cell.imageView.sd_setImage(with: URL(string: arrImageURLs[indexPath.item]))`

And, `didSelectItemAt` `let browser = SKPhotoBrowser(originImage: cell.imageView.image!, photos: imageURLs , animatedFromView: cell)`

Did you see the problem, in `cellForItemAt` method I have to use `arrImageURLs` in order to use `SDWebImage`.

And while `didSelectItemAt` method method I have to use `imageURLs` array which is array of `SKPhotoProtocol`

I want to use `SDWebImage` for loading & cacheing image & in order to show I want to use `SKPhotoBrowser` using single array of `SKPhotoProtocol`.

**Comment by erolando** [comment]
for me work next code:

if let photo =photoAtIndex(currentPage) as? SKPhoto {
     let urlString = NSURL(string: photo.photoURL)
     let image = photo.underlyingImage
 }

 in SKPhotBrowser.swift :

    private var currentPageIndex: Int = 0    //search this
    public var currentPage: Int {                  //and add this
        get {
            return currentPageIndex
        }
    }
