### ISSUE TITLE
Dismiss Animation to Origin

### ISSUE THREAD

**Issue by winkelsdorf** [suzuki-0000/SKPhotoBrowser#154]
Is there a way to dismiss the shown image back to the originImage/animatedFromView?

Using the latest swift 3 version I get a nice animation from the animatedFromView to the SKPhotoBrowser but when dismissing the image is just faded out.

Anything I'm missing?

**Comment by winkelsdorf** [comment]
Ah, what was missing in the Docs was in the example ;) Figured it out 👍

**Comment by UzumakiAlfredo** [comment]
I couldn't figured it out! what did you do !?????

**Comment by winkelsdorf** [comment]
@UzumakiAlfredo Have you had a look at the Example in the project? And its source?

I tried it and it works directly out of the box. `SKPhotoBrowserDelegate` has a method called `viewForPhoto`. 

In the example it's used with a `UICollectionView`.

Shouldn't be that difficult to implement.

hth!

<img width="1203" alt="Screen Shot 2019-04-11 at 09 48 24" src="https://user-images.githubusercontent.com/1413291/55939832-0e0def00-5c3f-11e9-87dd-f03766594f2f.png">

**Comment by UzumakiAlfredo** [comment]
Thanks ! now I see !!!!

**Comment by winkelsdorf** [comment]
Happy to help! You're welcome! 👍
