### ISSUE TITLE
Wrong StatusBar appearance with View controller-based status bar appearance

### ISSUE THREAD

**Issue by winkelsdorf** [suzuki-0000/SKPhotoBrowser#157]
When the App has ```View controller-based status bar appearance``` set to ```YES``` in ```Info.plist``` the statusbar handling of SKPhotoBrowser is broken (black on black).

This can be circumvented by using a subclass which implements ```preferredStatusBarStyle```.

For convenience, if anybody else runs into this problem:

```swift
import UIKit
import SKPhotoBrowser

open class ExtendedSKPhotoBrowser: SKPhotoBrowser {

    open override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent // white statusbar, .default is black
    }

}
```

Just instantiate ```ExtendedSKPhotoBrowser``` instead of ```SKPhotoBrowser```.

**Comment by winkelsdorf** [comment]
Closing and keeping it as a reference for further documentation here.

**Comment by DamascenoRafael** [comment]
I know it's an old issue, but just commenting to try to improve lib behavior.

The same behavior still continues here. I think the proposed solution should be default to display the status bar since the default background color is dark.
