### ISSUE TITLE
Button Position wrong with changed StatusBar handling

### ISSUE THREAD

**Issue by winkelsdorf** [suzuki-0000/SKPhotoBrowser#158]
With the removed StatusBar handling in the current version, the close button is too close to the statusbar:

<img width="651" alt="screenshot 2016-10-09 22 23 16" src="https://cloud.githubusercontent.com/assets/1413291/19223400/fcf1d790-8e6e-11e6-8c40-4e58d4f5d74b.png">

I know that SKButton.buttonTopOffset is responsible for this but as it's not meant to be subclassed this must be fixed in the repo.

Correct positioning can be seen in your demo images:
https://github.com/suzuki-0000/SKPhotoBrowser/blob/master/Screenshots/

**Comment by suzuki-0000** [comment]
thanks issue. well I need to check it

**Comment by suzuki-0000** [comment]
v4.0.1 will fix this problem. please create new issue if another problem occur

**Comment by twkong** [comment]
in v4.0.1, still too close from the statusbar.
