### ISSUE TITLE
Device lost conecction when double tap on UICollectionViewCell

### ISSUE THREAD

**Issue by vikht0r** [suzuki-0000/SKPhotoBrowser#159]
When i am trying to run application in the real device getting this error

Restore the connection to “iPhone” and run “My App” again, or if “My App” is still running, you can attach to it by selecting Debug > Attach to Process > My App.

This only happens when the view just loaded and immediately touched a cell two or more times quickly.

the device loses the connection. without any registration error.

I'm carrying more than 22 images, all in jpg compressed to the maximum, so I discard it memory problem.

In the simulator this problem does not occur.

 if selectedIndexPath.section == 0 {
            print("000000000000000000000000000000")

```
        //downloadURLPhotoAlbum()
        SKPhotoBrowserOptions.displayBackAndForwardButton = false
        SKPhotoBrowserOptions.displayAction = false
        let browser = SKPhotoBrowser(photos: self.imagesUrlSKPhotoAlbum)
        browser.initializePageIndex((selectedIndexPath as NSIndexPath).item)
        browser.delegate = self
        present(browser, animated: true, completion: {})

    }
    else if selectedIndexPath.section == 1{

        //downloadURLSelfies()
        print("11111111111111111111111111111")


        SKPhotoBrowserOptions.displayBackAndForwardButton = false
        SKPhotoBrowserOptions.displayAction = false
        let browser = SKPhotoBrowser(photos: self.imagesUrlSKSelfies)
        browser.initializePageIndex((selectedIndexPath as NSIndexPath).item)
        browser.delegate = self
        present(browser, animated: true, completion: {})

    }
```

**Comment by suzuki-0000** [comment]
please re-open if it'll occur latest version.
