### ISSUE TITLE
Could you give a sample code to show how to use custom cache with Kingfisher?

### ISSUE THREAD

**Issue by l12ab** [suzuki-0000/SKPhotoBrowser#160]
Just like the title, thanks

**Comment by suzuki-0000** [comment]
I haven't used kingfisher, so I'm not sure whether it can cache or good interface for this implement.

**Comment by ghysrc** [comment]
@l12ab I'm using Kingfisher in my project too. It's very easy to implement.

**First**, create a class extends SKImageCacheable. e.g:

class MyImageCache: SKImageCacheable {
    
    func imageForKey(_ key: String) -> UIImage? {
        return ImageCache.default.retrieveImageInDiskCache(forKey: key)
    }
    
    func setImage(_ image: UIImage, forKey key: String) {
        ImageCache.default.store(image, forKey: key)
    }
    
    func removeImageForKey(_ key: String) {
        ImageCache.default.removeImage(forKey: key)
    }
    
}

**Second**, set the custom cache to SKCache in AppDelegate. e.g:

`SKCache.sharedCache.imageCache = MyImageCache()`

**Comment by wlgemini** [comment]
You also need this to activate cache:
```swift
let photo = SKPhoto.photoWithImageURL(url)
photo.shouldCachePhotoURLImage = true
```

**Comment by jboulter11** [comment]
Resurrecting this dead issue because the `ImageCache.default.retrieveImageInDiskCache(forKey: key)` method has been deprecated.

Any plans to update the `SKImageCacheable` protocol to support the new `retrieveImageInDiskCache` method?

Here's an example of the usage we might need to support the latest Kingfisher implementation:
```swift
    func image(for key: String, completion: @escaping (UIImage?) -> Void) {
        ImageCache.default.retrieveImageInDiskCache(forKey: key) { result in
            switch result {
            case .success(let image):
                completion(image)
            case .failure(_):
                completion(nil)
            }
        }
    }
```

**Comment by jboulter11** [comment]
@suzuki-0000 any plans to update `imageForKey` to be asynchronous?
