### ISSUE TITLE
Background color doesn't work 

### ISSUE THREAD

**Issue by alexsanderkhitev** [suzuki-0000/SKPhotoBrowser#162]
Hello again=)
I try to use  `SKPhotoBrowserOptions.backgroundColor = .white` and `SKPhotoBrowserOptions.textAndIconColor = .black` from swift 3 branch but it doesn't work. How can I fix it? I use Xcode 8 and Swift 3

**Comment by suzuki-0000** [comment]
hey @alexsanderkhitev . meet again!
I haven't seen yet, have't time lately... hope you can fix and make pullrequest as you know this repo well

**Comment by suzuki-0000** [comment]
version 4.0.1 fixed this issue.
@ Josh-Bruce fixed this problem. thanks!
