### ISSUE TITLE
Long pictures should match the screen width by default

### ISSUE THREAD

**Issue by ghysrc** [suzuki-0000/SKPhotoBrowser#164]
![screen](https://cloud.githubusercontent.com/assets/4082752/19584726/4c0d0dbe-9779-11e6-8c4e-28aad5fcd9f1.jpg)

When the browser displays some very long pictures, it looks like this.
I think the picture's width should match the screen by default, so I can just scroll down to read the content without zoom it.
And I think a feature of set the max scale by SKPhotoBrowserOptions is useful too.

**Comment by suzuki-0000** [comment]
>And I think a feature of set the max scale by SKPhotoBrowserOptions is useful too.
I think so. will try to implement first.
