### ISSUE TITLE
Release for Swift 3 branch

### ISSUE THREAD

**Issue by barrault01** [suzuki-0000/SKPhotoBrowser#169]
Hi there you need to make a tag for the swift 3 branch if not nobody will be able to use SKPhotoBrowser inside a pod. You can do a beta tag like in moya repo : https://github.com/Moya/Moya/releases

**Comment by suzuki-0000** [comment]
I didn't even know that. thanks. I will try

**Comment by barrault01** [comment]
thanks :)

**Comment by suzuki-0000** [comment]
v4.0.0 will be swift 3.0. thanks issue
