### ISSUE TITLE
How to update the current Image?

### ISSUE THREAD

**Issue by alexanderkhitev** [suzuki-0000/SKPhotoBrowser#170]
Hello! My case. I show one photo in the browser and I'm after some action is necessary to replace it by another without closing the browser, how do I make it? Or you need to add new features?

**Comment by suzuki-0000** [comment]
hi alex! sorry I'm late.
there's no function of those, so need to add new function.
this is `photobrowser`, so acutually I don't want to add update/remove function anymore. just for `browse`.

**Comment by yeziahehe** [comment]
same qustion

**Comment by v-ken** [comment]
For anyone still looking for a solution, you can get the `SKPhoto` object from the browser and change its `underlyingImage` property.
