### ISSUE TITLE
Display Gallery as Collection View 

### ISSUE THREAD

**Issue by ahmadabudawod** [suzuki-0000/SKPhotoBrowser#176]
What is the configuration to display gallery as the following attached image.

![screen shot 2016-11-23 at 2 07 34 pm](https://cloud.githubusercontent.com/assets/862330/20559587/54074ee0-b186-11e6-90c7-3ed01a83d85a.png)

**Comment by suzuki-0000** [comment]
please refer example code at `/SKPhotoBrowserExample`
