### ISSUE TITLE
Unclear how placeholder image is supposed to work

### ISSUE THREAD

**Issue by irace** [suzuki-0000/SKPhotoBrowser#181]
When creating an `SKPhoto` with the `init(url: String, holder: UIImage?)` initializer, I would expect the `holder` to simply show up _until_ the photo located at the provided `url` is downloaded.

This does not seem to be the case, however. If an image is passed as the `holder` argument, it seems as though the photo located at the provided `url` is never fetched. 

Is this the desired behavior? It seems very strange – if this was what you wanted, you could just initialize an `SKPhoto` without the `url` entirely.

**Comment by suzuki-0000** [comment]
I imaged that when url fetch failed, use placeholder. 
but your issue is true enough. try to modify not only failed but also show up _until_ the photo located at the provided `url` is downloaded.

**Comment by suzuki-0000** [comment]
4.0.1 version fixed this issue. create new issue or re-open issue if another problem occur:)
