### ISSUE TITLE
Not correctly dismissed when providing viewForPhoto

### ISSUE THREAD

**Issue by shaljam** [suzuki-0000/SKPhotoBrowser#183]
When I use `viewForPhoto` present animation and dismiss animation work, but after dismiss view seems frozen. I think `SKPhotoBrowser` is not correctly dismissed.
I'm using `swift3` branch.

Edit: When not using `viewForPhoto` and dismissing using slide, after opening again the background is a little transparent.

**Comment by Artimuss** [comment]
+1 here

Dismiss with slide and open a photo again, background transparent and no buttons to share or to close

**Comment by suzuki-0000** [comment]
I may fix this issue at latest ver. 
As far as I checked latest ver it's not show. can you please check the latest and create new issue when it happens. thanks in advance.
