### ISSUE TITLE
Add New Button & Text to Top 

### ISSUE THREAD

**Issue by starsoheil2007** [suzuki-0000/SKPhotoBrowser#189]
Hi 
Can i add new Button or Text to top bar like delete button ?

**Comment by DanielBalsalobre** [comment]
Swift 3
`
        Sesion.browser = SKPhotoBrowser(photos: images)
       
        Sesion.browser?.delegate = self
        Sesion.browser?.initializePageIndex(Int((sender.view?.accessibilityIdentifier)!)!)
       
        let vistaNombrePrecio: UIView = UIView()
    
        vistaNombrePrecio.backgroundColor = Constantes.grisclaro.withAlphaComponent(0.5)
        vistaNombrePrecio.translatesAutoresizingMaskIntoConstraints = false
        Sesion.browser?.view.addSubview(vistaNombrePrecio)
        let margins = Sesion.browser?.view.layoutMarginsGuide
        vistaNombrePrecio.trailingAnchor.constraint(equalTo: (margins?.trailingAnchor)!).isActive = true
        vistaNombrePrecio.leadingAnchor.constraint(equalTo: (margins?.leadingAnchor)!).isActive = true
        vistaNombrePrecio.bottomAnchor.constraint(equalTo: (margins?.bottomAnchor)!, constant: -50).isActive = true
        vistaNombrePrecio.heightAnchor.constraint(equalToConstant: 50.0).isActive = true
`
