### ISSUE TITLE
Status bar problem

### ISSUE THREAD

**Issue by yarodevuci** [suzuki-0000/SKPhotoBrowser#195]
@suzuki-0000 
SKPhotoBrowserOptions.displayStatusbar = false 
Status bar is still shown

Please help

**Comment by twkong** [comment]
same here!

**Comment by LouisHors** [comment]
same here

**Comment by khoren93** [comment]
Setting 'View controller-based status bar appearance' to Yes in Info.plist file fixed this issue.
