### ISSUE TITLE
Problem about crash app

### ISSUE THREAD

**Issue by DanielLe232** [suzuki-0000/SKPhotoBrowser#198]
Hi all,
When i implement in my app.
It occur crash with error:
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]

I need help?
Thanks :)

**Comment by shinshichirou** [comment]
Any news about this?

**Comment by DanielLe232** [comment]
Hi shinshichirou,
Because I set UIImage nil
I fixed it.
Thank :)

**Comment by shinshichirou** [comment]
omg, this was so simple :D thank you
