### ISSUE TITLE
TableViewCell not show

### ISSUE THREAD

**Issue by truong15** [suzuki-0000/SKPhotoBrowser#2]
I try to using this image with url https://www.thuthuatweb.net/wp-content/uploads/baiviet/2014/01/windows-phone-loading-animation.png but the demo does not show anything.
Could you check this?

**Comment by suzuki-0000** [comment]
Hi, @truong15.  I will check this out

**Comment by suzuki-0000** [comment]
I think this is same issue as [here](https://github.com/suzuki-0000/SKPhotoBrowser/issues/1#issuecomment-155973007).
please see it, and some example i create [this branch](https://github.com/suzuki-0000/SKPhotoBrowser/tree/check/issue1).

**Comment by truong15** [comment]
Thank you for your help. It's a great library.
