### ISSUE TITLE
example project didn't work !

### ISSUE THREAD

**Issue by Mohammed-Eliass** [suzuki-0000/SKPhotoBrowser#203]
After downloading the example project and open the "example.xcodeproj" Xcode told me to install SDWebImage to sync with Podfile, but after installing pod and opening the project with "example.xcworkspace", when I run the project nothing happened !

so any help, what should I do ?

**Comment by suzuki-0000** [comment]
Can you please test for latest version and xcode?  Please create new issue if it's still happen.
