### ISSUE TITLE
Zoom while rotating big image

### ISSUE THREAD

**Issue by ferostar** [suzuki-0000/SKPhotoBrowser#209]
When rotating the device and the browser is showing a big image, it zooms in and out while rotating. Not sure if this is an animation feature, but would love a easy way to handle rotation without it. Nothing big, is this possible? Looked and looked but couldn't find a property to handle this. Thanks!

**Comment by g-balas** [comment]
Any new about this ?

**Comment by RubenKid** [comment]
I'm experiencing same issue

**Comment by suzuki-0000** [comment]
Sorry for late reply. Maybe It will not appear for latest ver? please check it and create new issue it still shows.
