### ISSUE TITLE
dismissing while landscape changes presenting vc orientation

### ISSUE THREAD

**Issue by shinshichirou** [suzuki-0000/SKPhotoBrowser#211]
dismissing photo browser while landscape orientation changes the presenting view controller orientation to landscape, then it is set to be portrait only

**Comment by tarigancana** [comment]
@shinshichirou did you solve this problem ?

**Comment by suzuki-0000** [comment]
As far as I checked at latest version using example, It works properly. 
Can you please check it? thanks in advance.
