### ISSUE TITLE
Delegate function didShowPhotoAtIndex didn't work

### ISSUE THREAD

**Issue by DanielBalsalobre** [suzuki-0000/SKPhotoBrowser#212]
This is because an error on documentation:

Instead **func didShowPhotoAtIndex(index: Int) {**

Use **func didShowPhotoAtIndex(_ index: Int) {**

**Comment by Menthuss** [comment]
The same thing applies to the removePhoto delegate function:

Instead of using **func removePhoto(index: Int, reload: (() -> Void))**,

use **func removePhoto(_ browser: SKPhotoBrowser, index: Int, reload: @escaping (() -> Void))**

**Comment by suzuki-0000** [comment]
Thanks advice, I'll update readme.md
