### ISSUE TITLE
Memory is not released

### ISSUE THREAD

**Issue by rogomantik** [suzuki-0000/SKPhotoBrowser#219]
I start it from a collectionView with 100+ images, someone bigger than 5MB
`SKPhotoBrowser(originImage: images[indexPath.row].underlyingImage, photos: images, animatedFromView: cell)`
when select a cellview the browsers shows but when I scroll the images the memory occupation continues to increase until the app crashes for excessive memory usage (500+MB)
the memory of the not visible images don't seem to be released and neither the browser itself when closed

using ios 10.3.2

**Comment by embassem** [comment]
+1

**Comment by alexanderkhitev** [comment]
+1

**Comment by alexanderkhitev** [comment]
@rogomantik did you solve this problem?

**Comment by rogomantik** [comment]
@alexanderkhitev no. I'm using https://github.com/thiagoperes/IDMPhotoBrowser with various modifications. I also tested https://github.com/CodeEagle/SSImageBrowser but have the same memory issues. Probably the problem is Swift related

**Comment by alexanderkhitev** [comment]
@rogomantik thanks for response. I'm sure this is not not a Swift problem.

**Comment by suzuki-0000** [comment]
Same issue here, it most like fixed for latest 
https://github.com/suzuki-0000/SKPhotoBrowser/issues/294
