### ISSUE TITLE
Device rotation doesn't refresh visible imageview frames

### ISSUE THREAD

**Issue by turushanaktay** [suzuki-0000/SKPhotoBrowser#22]
After device rotation if you change between images all are good but current image frame for initial state (after first rotation) is not good, have to be refreshed

**Comment by suzuki-0000** [comment]
@turushanaktay  thanks for issue. I will fix it.

**Comment by dasoga** [comment]
I have a question, is not a issue:

All of my app is in portrait mode, I want to permit in landscape only the browser photo.

I put this in my AppDelegate:

    func application(application: UIApplication, supportedInterfaceOrientationsForWindow window: UIWindow?) -> UIInterfaceOrientationMask {
        if self.window?.rootViewController?.presentedViewController is SKPhotoBrowser {            
            let secondController = self.window!.rootViewController!.presentedViewController as! SKPhotoBrowser            
            if (secondController.presentedViewController != nil) {
                return UIInterfaceOrientationMask.All
            }else{
                return UIInterfaceOrientationMask.Portrait
            }
        } else {
            return UIInterfaceOrientationMask.Portrait
        }        
    }

But doesn't work :S 
Can you help me to put only in this window the landscape option?
Thanks for help!

**Comment by alexsanderskywork** [comment]
Hi @dasoga 
You must to write this code in class which is showing SKPhotoBrowser. I checked it for me and it works.

 override func shouldAutorotate() -> Bool {
        super.shouldAutorotate()
        if presentedViewController?.isKindOfClass(SKPhotoBrowser) != nil {
            return false
        } else {
            return true
        }
    }

**Comment by dasoga** [comment]
Thanks for response!

But doesn't work:
How do you have configure your project?
I have this: 

In my Info.plist:

	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>

I have two view controllers:

OneViewController -> push -> SecondViewController (in this create photo browser)

In SecondViewController:

I have my collection view and in method didSelectItem, create photo browser:

    func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
        guard let cell = collectionView.cellForItemAtIndexPath(indexPath) as? GalleryCollectionViewCell else {
            return
        }
        guard let originImage = cell.imageView.image else {
            return
        }
        
        let browser = SKPhotoBrowser(originImage: originImage, photos: imagesArray, animatedFromView: cell)
        browser.initializePageIndex(indexPath.row)
        browser.delegate = self

        browser.displayAction = true
        browser.displayBackAndForwardButton = false
        dispatch_async(dispatch_get_main_queue()) { 
            self.presentViewController(browser, animated: true, completion: {})
        }
        
    }

I implemented the method 

 override func shouldAutorotate() -> Bool {
        super.shouldAutorotate()
        if presentedViewController?.isKindOfClass(SKPhotoBrowser) != nil {
            return false
        } else {
            return true
        }
    }

But it doesn't call the method.

I created a new project to test, but the same issue, how do you configure to get it work?
Thanks!
Regards!

**Comment by alexsanderskywork** [comment]
My class

`import UIKit
````

class ViewController: UIViewController, SKPhotoBrowserDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        self.definesPresentationContext = true
    
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    //
    
    
    // it doesn't work
    override func supportedInterfaceOrientations() -> UIInterfaceOrientationMask {
        super.supportedInterfaceOrientations()
        if presentedViewController?.isKindOfClass(SKPhotoBrowser) != nil {
            print("not nil support")
            return UIInterfaceOrientationMask.LandscapeLeft
        } else {
            print("nil")
            return UIInterfaceOrientationMask.All
        }
    }
    
    override func shouldAutorotate() -> Bool {
        super.shouldAutorotate()
        if presentedViewController?.isKindOfClass(SKPhotoBrowser) != nil {
            print("not nil automate")
            return false
        } else {
            print("nil")
            return true
        }
    }
    
    @IBAction func showImages(sender: UIButton) {
        let red = UIImage(named: "red.jpg")!
        let deadpool = UIImage(named: "deadpool.jpg")!
        let star = UIImage(named: "Star.jpg")!
        let first = SKPhoto.photoWithImage(red)
        let second = SKPhoto.photoWithImage(dead pool
        let third = SKPhoto.photoWithImageURL("http://www.bkfonbet.com/images/formula1/formula1.jpg")
        let fourth = SKPhoto.photoWithImage(star)
        let photoArray = [fourth, first, second, third]
        let browser = SKPhotoBrowser(photos: photoArray)
        browser.delegate = self
        browser.displayDeleteButton = false
        browser.isForceStatusBarHidden = true
        presentViewController(browser, animated: true, completion: nil)
    }

    
    func removePhoto(browser: SKPhotoBrowser, index: Int, reload: (() -> Void)) {
        print("delete index", index)
    }
    
    func didShowPhotoAtIndex(index: Int) {
        print("did show photo at index", index)
    }
}

```)

**Comment by alexsanderskywork** [comment]
hello @dasoga 
My class

```
import UIKit

class ViewController: UIViewController, SKPhotoBrowserDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        self.definesPresentationContext = true
    
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    //
    
    
    // it doesn't work
    override func supportedInterfaceOrientations() -> UIInterfaceOrientationMask {
        super.supportedInterfaceOrientations()
        if presentedViewController?.isKindOfClass(SKPhotoBrowser) != nil {
            print("not nil support")
            return UIInterfaceOrientationMask.LandscapeLeft
        } else {
            print("nil")
            return UIInterfaceOrientationMask.All
        }
    }
    
    override func shouldAutorotate() -> Bool {
        super.shouldAutorotate()
        if presentedViewController?.isKindOfClass(SKPhotoBrowser) != nil {
            print("not nil automate")
            return false
        } else {
            print("nil")
            return true
        }
    }
    
    @IBAction func showImages(sender: UIButton) {
        let red = UIImage(named: "red.jpg")!
        let deadpool = UIImage(named: "deadpool.jpg")!
        let star = UIImage(named: "Star.jpg")!
        let first = SKPhoto.photoWithImage(red)
        let second = SKPhoto.photoWithImage(dead pool
        let third = SKPhoto.photoWithImageURL("http://www.bkfonbet.com/images/formula1/formula1.jpg")
        let fourth = SKPhoto.photoWithImage(star)
        let photoArray = [fourth, first, second, third]
        let browser = SKPhotoBrowser(photos: photoArray)
        browser.delegate = self
        browser.displayDeleteButton = false
        browser.isForceStatusBarHidden = true
        presentViewController(browser, animated: true, completion: nil)
    }

    
    func removePhoto(browser: SKPhotoBrowser, index: Int, reload: (() -> Void)) {
        print("delete index", index)
    }
    
    func didShowPhotoAtIndex(index: Int) {
        print("did show photo at index", index)
    }
}

```)

**Comment by alexsanderskywork** [comment]
@dasoga  I didn't touch info.plist

**Comment by dasoga** [comment]
@alexsanderskywork Ok! got it.
But with that, your ViewController doesn't rotate but your photo browser do it, right?
I'm trying to do it now. Thanks!

**Comment by dasoga** [comment]
@alexsanderskywork not working dude...

My ViewController rotate too, but I want rotate only SKPhotoBrowser
Thanks for your help, I'm looking another alternative.

My Class:

    import UIKit
    import SKPhotoBrowser

    class ViewController: UIViewController, SKPhotoBrowserDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        self.definesPresentationContext = true
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    

    override func shouldAutorotate() -> Bool {
        print("should rotate")
        super.shouldAutorotate()
        if presentedViewController?.isKindOfClass(SKPhotoBrowser) != nil {
            print("not nil automate")
            return false
        } else {
            print("nil")
            return true
        }
    }
    
    
    @IBAction func pushView(sender:AnyObject){
        let third = SKPhoto.photoWithImageURL("http://www.bkfonbet.com/images/formula1/formula1.jpg")
        let photoArray = [third]
        let browser = SKPhotoBrowser(photos: photoArray)
        browser.delegate = self
        browser.displayDeleteButton = false
        browser.isForceStatusBarHidden = true
        presentViewController(browser, animated: true, completion: nil)
        
    }

    }

**Comment by alexsanderskywork** [comment]
@dasoga please write your resolution here
