### ISSUE TITLE
Padding properties no longer exist

### ISSUE THREAD

**Issue by igorkulman** [suzuki-0000/SKPhotoBrowser#228]
The padding properties `imagePaddingX` and `imagePaddingY` seem to no longer exist, is there any alternative?

The problem is that when the control displays and iPhone screenshot that fits the screen exactly, the share button and the close button are drawn over the image and not really visible.

**Comment by suzuki-0000** [comment]
At least now, we don't have that.
`SKPhotoBrowserOptions.closeAndDeleteButtonPadding` is the only things you can move the close button for `X`.
