### ISSUE TITLE
For long captions uitextview would be better instead of uilabel

### ISSUE THREAD

**Issue by turushanaktay** [suzuki-0000/SKPhotoBrowser#23]
If a photo has long caption, it goes over photo, an uitextview with maximum line option would be better for captions.

**Comment by suzuki-0000** [comment]
@turushanaktay. I'll fix it too :+1:  but priority is lower than others. pull request is always welcome:)

**Comment by suzuki-0000** [comment]
label's string goes over photo is worst, so I adapt .ByTruncatingTail for it now. 
whether I should use `adjustsFontSizeToFitWidth` or not is next problem anyway.

**Comment by turushanaktay** [comment]
ah you are right, I just edited label's line number to zero, that's why it went over photo, but edited into uitextview edition already but code is not well organized I must clean it before pull :)
