### ISSUE TITLE
iPhone X safe area overlay

### ISSUE THREAD

**Issue by timroesner** [suzuki-0000/SKPhotoBrowser#235]
I noticed a problem on the iPhone X where your toolbar and close/delete buttons overlay with the safe area, meaning interfering with the status bar and the home bar indicator. Below is a screenshot

![simulator screen shot - iphone x - 2017-09-12 at 14 29 23](https://user-images.githubusercontent.com/13894518/30349224-04f255de-97c7-11e7-9d22-e3156c95bdb5.png)

**Comment by anushkmittal** [comment]
Any quick fix suggestions till we get the next pods release?

**Comment by timroesner** [comment]
So I just created PR #239 which fixes this. If you just have top buttons and no toolbar you can actually use the closeAndDeleteButtonPadding property to adjust the padding. 

If you need an immediate fix and don't like adjusting the values yourself you can use the following in your pod file to update temporarily: 
`pod 'SKPhotoBrowser', :git => 'https://github.com/timroesner/SKPhotoBrowser', :commit => 'bd169f9'`

Here is a screenshot of the fix: 
![simulator screen shot - iphone x - 2017-09-15 at 15 53 29](https://user-images.githubusercontent.com/13894518/30506283-86035cd0-9a2f-11e7-8f3b-596c706f63fd.png)

**Comment by anushkmittal** [comment]
Thanks for helping out 😊. Another minor UI issue, the caption text (page number) and side arrows are off-center w.r.t to the swipe up bar. #240
