### ISSUE TITLE
Loading more photo after present

### ISSUE THREAD

**Issue by powhu** [suzuki-0000/SKPhotoBrowser#24]
Thank you. Nice project.

Can you add a method to load more photos after browser presented.

Something like
```
browser.appendPhotos([SKPhoto])
browser.reloadData()
```

**Comment by suzuki-0000** [comment]
hi @powhu, I will think about it.

**Comment by alexsanderkhitev** [comment]
Hello! @suzuki-0000 
I don't get this error. Is it fixed?
