### ISSUE TITLE
Some methods needs @objc

### ISSUE THREAD

**Issue by lynnx4869** [suzuki-0000/SKPhotoBrowser#243]
I use SKPhotoBrowser(v4.1.1) in Xcode9 with CocoaPods, But there are some errors in new Xcode. Like Argument of '#selector' refers to instance method 'handleDoubleTap' that is not exposed to Objective-C etc...
I use v4.1.0 well, what's happen? Thank you.

**Comment by lynnx4869** [comment]
@suzuki-0000 When supports Swift4?

**Comment by swaterfall** [comment]
@suzuki-0000 I'm getting this issue as well with CocoaPods, switching to the swift4 branch didn't help.

**Comment by suzuki-0000** [comment]
it supports at v5.0.0(5 Oct 2017). please use it, thanks!
