### ISSUE TITLE
Delegate call issue & SKPhotoBrowserOptions bug

### ISSUE THREAD

**Issue by nCr78** [suzuki-0000/SKPhotoBrowser#244]
Hello! I have to start by saying that this is an incredible project!

Now, in the last versions, it seems that you've removed the delegate call inside 'open func determineAndClose()' at SKPHotoBrowser.swift @ line 238. It should be:

`open func determineAndClose() {`
`delegate?.willDismissAtPageIndex?(currentPageIndex)`
`animator.willDismiss(self)`
`}`

Apparently you've also changed some of your if parameters to not look at SKPhotoBrowserOptions at all (example: display delete button) and correct me if I'm wrong, but there are no proper setters for the SKPhotoBrowser boolean.

**Comment by suzuki-0000** [comment]
Thanks your feedback(sorry for late reply), it maybe fixed at latest ver. let me know if you have any issues there. 

https://github.com/suzuki-0000/SKPhotoBrowser/blob/e8af321d593b76eb27cdd52526e482678af0fd20/SKPhotoBrowser/SKPhotoBrowser.swift#L217
