### ISSUE TITLE
SKPhotoBrowserOptions bug

### ISSUE THREAD

**Issue by BrettWPather** [suzuki-0000/SKPhotoBrowser#249]
SKPhotoBrowserOptions.displayCounterLabel = true
SKPhotoBrowserOptions.displayBackAndForwardButton = true      

Some options don't work in release 4.1.1
I think you have introduced a bug cause I reverted back to 4.1.0 and they worked fine.

I am not sure why, please give some feedback

**Comment by l12ab** [comment]
same issue, so i fall back to 4.0.1.

and i have a question, counterlabel will be hidden after 4 seconds by default, i don't want it to be hidden, how to set it?

**Comment by sudeshgutta** [comment]
I'm facing a similar issue with SKPhotoBrowserOptions on 4.1.1, none of the options I set are actually getting configured

**Comment by Codeido** [comment]
Same here. On version 4.1.0 all is ok

**Comment by jsmvalente** [comment]
Same here, SKPhotoBrowserOptions are not being taken into account. For example this line:
https://github.com/suzuki-0000/SKPhotoBrowser/blob/819157ccabba815cd02e86c12c816f8ecabcda87/SKPhotoBrowser/SKToolbar.swift#L65 

used to depend on SKPhotoBrowserOptions. It doesn't now.

**Comment by igorkulman** [comment]
Looking at the code, it is also needed to call `showToolbar(bool: true)` on the `SKPhotoBrowser`instance in addition to settings those two flags. This works for me with the current version.

**Comment by suzuki-0000** [comment]
Sorry for late reply, It may be fixed at v5.x.x so I closed
