### ISSUE TITLE
SKPhotoBrowserOptions.displayDeleteButton not working

### ISSUE THREAD

**Issue by filograno** [suzuki-0000/SKPhotoBrowser#251]
I've noted that `SKPhotoBrowserOptions.displayDeleteButton` is not used in 5.0.0 release and previous.
At the moment I am forced to use the method `showDeleteButton(bool: true)` of the SKPhotoBrowser class in order to see a delete button in the photo browser view.

By doing a little investigation this behavior is broken by the pull request #227 and specifically by the commit 7081a3f3ecbeece4addf380d5fe317339f18ed6c

**Comment by justinguo** [comment]
Same issue here. Also true for showToolbar option.

**Comment by ICCanche** [comment]
Same issue, I thought it was an iOS 11 compatibility error.

**Comment by suzuki-0000** [comment]
Sorry for late reply. 
I refactored at v5.0.2, so that now it `showDeleteButton` is removed and you can use `SKPhotoBrowserOptions.displayDeleteButton` properly. 
see check code below. 

https://github.com/suzuki-0000/SKPhotoBrowser/blob/master/SKPhotoBrowser/SKActionView.swift#L106
