### ISSUE TITLE
SKPhotoBrowser not working for Xcode 9 / swift 4 - NEED urgent help !!!!

### ISSUE THREAD

**Issue by siddharthadeb** [suzuki-0000/SKPhotoBrowser#254]
Giving me CRASH -- NEED HELP
SKPhotoBrowser not working for Xcode 9 / swift 4 - NEED urgent help !!!!

**Comment by fabrizotus** [comment]
Works for me but does not show toolbar, action button and navigation buttons
In iOS 10 and 11

Attachment differences from controls in xcode 8 and xcode 9

XCODE 8
<img width="309" alt="xcode8" src="https://user-images.githubusercontent.com/2091193/31795072-dbfbdd84-b4fa-11e7-9c59-0db8eca86599.png">

XCODE 9
<img width="320" alt="xcode9" src="https://user-images.githubusercontent.com/2091193/31795083-e22fae1a-b4fa-11e7-91a2-a2f985e8b594.png">

**Comment by Faydee1220** [comment]
I found a weird problem, every time I use "pod update". SKPhotoBrowser's Swift Language Version always back to 3.2, I need to update it to 4.0 every time.

**Comment by ysoftware** [comment]
@fabrizotus in 5.0 you can show toolbar using

` browser.showToolbar(bool: true)`

**Comment by fabrizotus** [comment]
@ysoftware , it working.
Many thanks.

**Comment by yarodevuci** [comment]
@ysoftware Thanks!!

**Comment by siddharthadeb** [comment]
@fabrizotus  - how its working for ios 11 xcode 9.1 with development version 9.0 to latest. as I get didShowPhotoAtIndex:_index:]: unrecognized selector sent to instance .. issue.. Please help me out on this. URGENT !!!

**Comment by DavidLari** [comment]
I just updated to 5.0.3 and now browser.showToolbar(bool: true) doesn't compile. Kind of frustrated with these breaking changes on these small point releases.
