### ISSUE TITLE
didShowPhotoAtIndex delegate

### ISSUE THREAD

**Issue by rockade** [suzuki-0000/SKPhotoBrowser#26]
Nice project. Thank you! The didShowPhotoAtIndex delegate is marked as a required. I think it should be marked as optional.

**Comment by suzuki-0000** [comment]
hi @rockade, thanks your issue. yeah I will fix it

**Comment by suzuki-0000** [comment]
@rockade tag 1.4.2 or latest master is fixed this issue.

**Comment by rockade** [comment]
Thank you!
