### ISSUE TITLE
displayAction is not shown

### ISSUE THREAD

**Issue by yarodevuci** [suzuki-0000/SKPhotoBrowser#260]
iOS 11 XCode 9.1
SKPhotoBrowserOptions.displayAction = true, not showing the action button

**Comment by AnnatarHe** [comment]
same issue here

**Comment by maziyarpanahi** [comment]
None of these options change anything in iOS 11 Xcode 9 for me:

```
SKPhotoBrowserOptions.displayToolbar = true
SKPhotoBrowserOptions.displayCounterLabel = true
SKPhotoBrowserOptions.displayBackAndForwardButton = true
SKPhotoBrowserOptions.displayAction = true
```

**Comment by yarodevuci** [comment]
@maziyarpanahi Agreed..

**Comment by Codeido** [comment]
Same issue here

**Comment by yarodevuci** [comment]
Sometimes it is show but when clicking on it, then the app will crash....

**Comment by suzuki-0000** [comment]
Can you please use latest version, It's already fixed. sorry for being late reply!
