### ISSUE TITLE
How do I save the photo album

### ISSUE THREAD

**Issue by JianWenXie** [suzuki-0000/SKPhotoBrowser#266]
How do I save the photo album 
Hope to add a long press save to photo album features

**Comment by DuckDeck** [comment]
yes , I hope add save or download image feature

**Comment by suzuki-0000** [comment]
Please use 
`SKPhotoBrowserOptions.displayAction = true` 

There's no long press gesture so that I create a ticket. 
https://github.com/suzuki-0000/SKPhotoBrowser/issues/303

This is open source, so pull request is always welcome.
