### ISSUE TITLE
After dismiss there us gui glitch 

### ISSUE THREAD

**Issue by sakshigidwani93** [suzuki-0000/SKPhotoBrowser#267]
On tap of collection view cell i hve called the library. But if there are images whose height is big then after dismiss the navigation bar has gui glitch

**Comment by UmaMadhavi** [comment]
@sakshigidwani93 . I too have similar kind of issue .

**Comment by suzuki-0000** [comment]
#288, [5.0.5](https://github.com/suzuki-0000/SKPhotoBrowser/releases/tag/5.0.5)  may fix this issue,  can you please check it? thanks in advance.
