### ISSUE TITLE
Custom UIView injection

### ISSUE THREAD

**Issue by dubayb** [suzuki-0000/SKPhotoBrowser#269]
I would love to be able to have a delegate method to insert a custom UIView. Any hints on how I could go about doing this?

**Comment by suzuki-0000** [comment]
Please check at delegate, there's some delegate can create a custom UIView. At this time this is all for now. Thanks in advance! 

https://github.com/suzuki-0000/SKPhotoBrowser/blob/master/SKPhotoBrowser/SKPhotoBrowserDelegate.swift
