### ISSUE TITLE
Do u have a plan to add a Delete icon in right of  nav bar  

### ISSUE THREAD

**Issue by offbye** [suzuki-0000/SKPhotoBrowser#27]
Do u have a plan to add a Delete icon in right of  nav bar  ?
If not , I will add it.

**Comment by suzuki-0000** [comment]
hi @offbye. I don't have a plan of it. please add it :smiley:

**Comment by offbye** [comment]
I have finished the feature，and created a pull request

**Comment by suzuki-0000** [comment]
@offbye  thanks your PR! tag 1.4.4 or latest master is so.
