### ISSUE TITLE
iOS11.1.1系统访问相册崩溃

### ISSUE THREAD

**Issue by zhangjianjun056** [suzuki-0000/SKPhotoBrowser#275]
你好，请问在iOS11.1.1系统上面，访问相册崩溃，添加了NSPhotoLibraryUsageDescription、NSPhotoLibraryAddUsageDescription字段也是不起作用，请大神看看，有什么好的解决办法没？

**Comment by suzuki-0000** [comment]
Please write as english, can't read. 🤔  This issue closed, so please open new issue.
