### ISSUE TITLE
Unable to manually import SKPhotoBrowser into new project

### ISSUE THREAD

**Issue by dudduss** [suzuki-0000/SKPhotoBrowser#28]
<img width="1279" alt="screen shot 2016-02-19 at 11 18 35 pm" src="https://cloud.githubusercontent.com/assets/9653576/13195152/2b66af50-d75f-11e5-963a-8ebb2c41880b.png">

As you can see from the image above, I have manually dragged the SKPhotoBrowser code into my clean project, but it is not able to recognize the SKPhotoBrowser module for some reason. Any guidance on this?

**Comment by suzuki-0000** [comment]
hi @dudduss, I fixed for manually import. so download latest master, and you don't need `import` sentence at line 10.

**Comment by dudduss** [comment]
I tried it again, but it did not work. It is possible that I am importing the files into my project in the incorrect way.

![screen shot 2016-02-24 at 1 28 50 am 2](https://cloud.githubusercontent.com/assets/9653576/13280987/fb22f5e4-da95-11e5-89de-daa766979c81.png)

I've also tried this:

<img width="1280" alt="screen shot 2016-02-24 at 1 29 29 am" src="https://cloud.githubusercontent.com/assets/9653576/13280995/1077bd9e-da96-11e5-8c61-06e3e6d2e0b9.png">

**Comment by suzuki-0000** [comment]
How about just drag and drop the folder? 
![example](https://cloud.githubusercontent.com/assets/1096585/13307553/8b91e7ce-dbaf-11e5-8328-dc1571698233.gif)

**Comment by dudduss** [comment]
Thank you so much. My issue was not checking "Create Groups"...Why do I need to do that?

**Comment by krummler** [comment]
This isn't really a issue with the library. Either way. I would recommend using Cocoapods or Carthage to manage libraries. If you do not want to depend on external libraries, you can create a fork and point directly to it (at least in CocoaPods, I don't have any experience with Carthage), in example:

`pod 'SKPhotoBrowser', :git => 'https://github.com/krummler/SKPhotoBrowser', :branch => 'master'`
