### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by alexanderkhitev** [suzuki-0000/SKPhotoBrowser#294]
![memory leaks](https://user-images.githubusercontent.com/12511909/36645620-04da6b22-1a85-11e8-888d-9283369b6b81.png)

After viewing the photos and after `SKPhotoBrowser` has disappeared, `SKZoomingScrollView` does not disappear from memory

**Comment by suzuki-0000** [comment]
Hi, I checked using latest version, there's no memory leak, at least using example what I created. (Of course deinit will be called when SKPhotobrowser disappeared)

So please add xcode ver and your situation if it's still happend.  Thanks in advance.

<img width="1281" alt="2018-04-03 11 12 59" src="https://user-images.githubusercontent.com/1096585/38225476-0c07c06c-3730-11e8-8e72-dd3932eb8720.png">
<img width="1291" alt="2018-04-03 11 12 23" src="https://user-images.githubusercontent.com/1096585/38225477-0c423c56-3730-11e8-9ea1-b6eb3f1a570a.png">
