### ISSUE TITLE
crash in SKPaginationView

### ISSUE THREAD

**Issue by rayjun83** [suzuki-0000/SKPhotoBrowser#295]
display only one photo or set SKPhotoBrowserOptions.displayBackAndForwardButton = false

override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        if let view = super.hitTest(point, with: event) {
            if counterLabel.frame.contains(point)
                || prevButton.frame.contains(point) //crash here: Fatal error: Unexpectedly found nil while unwrapping an Optional value
                || nextButton.frame.contains(point) {
                return view
            }
            return nil
        }
        return nil
    }

**Comment by arnaudWasappli** [comment]
Same for me

**Comment by micmdk** [comment]
We're seeing the same - unfortunately it's our top crash at the moment.

@suzuki-0000 Could we get this (https://github.com/suzuki-0000/SKPhotoBrowser/pull/292) PR merged in? Or fixed in some other way? Thanks 👍

**Comment by suzuki-0000** [comment]
thanks for PR. I merged and v5.0.6 is published. Please check it 🙏
