### ISSUE TITLE
Wrong zoom when touch the black area

### ISSUE THREAD

**Issue by alexsanderskywork** [suzuki-0000/SKPhotoBrowser#30]
Wrong zoom when touch the black area. But I found a solution to the problem. I'm counting on interest clicking on the black area and bear the interest on the image. Also, the image may have a height greater than that of the device in pixels. So I decided to divide the height of the screen into two. Further, if a touch on the black area was in the range of less than half of the screen, Y is equals 0, if more than half of the screen, Y equals image height in pixels. It need to add in SKZoomingScrollView. I hope that it helps you. Thanks

```
func handleDoubleTap(view: UIView, touch: UITouch) {
        let needPoint = getViewFramePercent(view, touch: touch)
        handleDoubleTap(needPoint)
    }

  private func getViewFramePercent(view: UIView, touch: UITouch) -> CGPoint {
        let oneWidthViewPercent = view.bounds.width / 100
        let viewTouchPoint = touch.locationInView(view)
        let viewWidthTouch = viewTouchPoint.x
        let viewPercentTouch = viewWidthTouch / oneWidthViewPercent
        
        let photoWidth = photoImageView.bounds.width
        let onePhotoPercent = photoWidth / 100
        let needPoint = viewPercentTouch * onePhotoPercent
        
        var Y: CGFloat!
        
        if viewTouchPoint.y < view.bounds.height / 2 {
            Y = 0
        } else {
            Y = photoImageView.bounds.height
        }
        let allPoint = CGPoint(x: needPoint, y: Y)
        return allPoint
    }
```

**Comment by suzuki-0000** [comment]
hi, @alexsanderskywork
I haven't realized that zooming in a black area has a bug... your code is correctly fixed this bug.
thanks for your advice. 
latest master or tag 1.4.5 is fixed this bug.

**Comment by alexsanderskywork** [comment]
hi @suzuki-0000 
You can to close this bug)
