### ISSUE TITLE
SKPhotoBrowserOptions.displayCounterLabel is not working

### ISSUE THREAD

**Issue by shoby** [suzuki-0000/SKPhotoBrowser#301]
I tried to use the `SKPhotoBrowserOptions.displayCounterLabel` option.
However It doesn't seem to work.

I think the option was deleted while refactoring.

Now, no codes refer to the option except for declaration.
I found that `SKPhotoBrowserOptions.displayCounterLabel` was deleted in this commit.

https://github.com/suzuki-0000/SKPhotoBrowser/commit/6564bee0a9f85000f57417e2b8904af6f1aabb88

**Comment by suzuki-0000** [comment]
Thanks for your report. 
This is fixed at 5.0.7.
