### ISSUE TITLE
Delete and Close Button Overlapping bug

### ISSUE THREAD

**Issue by anilios** [suzuki-0000/SKPhotoBrowser#311]
See attached image, Delete button is overlapping close button.
I have a list of images to showcase in the app and needs to show delete button dynamically on some of the images based on the owner of the image. But it seems that the latest library 5.0.9 does have this UI bug. Please let me know if anything is wrong in my code.

I have used following options to show both buttons in my code: 

` SKPhotoBrowserOptions.swapCloseAndDeleteButtons = true
SKPhotoBrowserOptions.displayStatusbar = false
SKPhotoBrowserOptions.displayCloseButton = true
SKPhotoBrowserOptions.displayDeleteButton = true`

![screen shot 2018-04-24 at 10 29 56 am](https://user-images.githubusercontent.com/694814/39167103-f4e96e40-47aa-11e8-957b-8d4b63f22e27.png)

**Comment by anilios** [comment]
See attached image of the code, which is the cause of the bug, I have updated it manually in my code. also attached image of the corrected code.
![screen shot 2018-04-24 at 12 17 28 pm](https://user-images.githubusercontent.com/694814/39170628-d8865222-47b9-11e8-94a3-914d8cb6f74d.png)
![screen shot 2018-04-24 at 12 19 16 pm](https://user-images.githubusercontent.com/694814/39170630-d8bd5a60-47b9-11e8-9d76-7a3f1e772b2b.png)

**Comment by suzuki-0000** [comment]
let me close this issue. (has been merged.) thanks for your cooperation!
