### ISSUE TITLE
SKPhoto.photoWithImageURL(imageUrl, holder: holderImage)  not working

### ISSUE THREAD

**Issue by xiaoweiFive** [suzuki-0000/SKPhotoBrowser#316]
hello：
SKPhoto.photoWithImageURL(imageUrl, holder: holderImage) 
Cannot load network pictures

**Comment by xiaoweiFive** [comment]
@slav123 @

**Comment by xiaoweiFive** [comment]
![1526956791285](https://user-images.githubusercontent.com/17330916/40339352-a76d1154-5dac-11e8-9c11-dc98c938136e.jpg)

![1526956821520](https://user-images.githubusercontent.com/17330916/40339356-aceb82c8-5dac-11e8-8312-ac7f9a8075d6.jpg)

I found that I could not load the network picture, only show the bitmap.
Please look at the picture information
Thank you

**Comment by xiaoweiFive** [comment]
@hebertialmeida  @pj4533  @cheungpat  @VahanMargaryan  @slav123 
Thanks very much

**Comment by tracy-e** [comment]
+1

**Comment by purepure** [comment]
+1
