### ISSUE TITLE
updateDeleteButton / updateCloseButton Crashes

### ISSUE THREAD

**Issue by jsahoo** [suzuki-0000/SKPhotoBrowser#320]
Trying to update the delete or close button results in the following crash:
`Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`
Nothing else is printed to the console so this is all of the information that I have.

It crashes when trying to use an image literal:
`browser.updateDeleteButton(#imageLiteral(resourceName: "assetName"))`
a UIImage:
`browser.updateDeleteButton(UIImage(named: "assetName"))`
and an empty UIImage (as demonstrated in the documentation):
`browser.updateDeleteButton(UIImage())`

**Comment by klaus01** [comment]
Temporary solution:
``` swift
let browser = SKPhotoBrowser(photos: images, initialPageIndex: indexPath.row)
DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
    browser.updateCloseButton(UIImage(named: "fatie_close")!, size: CGSize(width: 44, height: 44))
}
present(browser, animated: true, completion: nil)
```

**Comment by jsahoo** [comment]
Sorry I forgot to update this after I discovered the solution. `updateCloseButton()` has to be called _after_ presenting the `SKPhotoBrowser`:

```swift
present(browser, animated: true, completion: nil)
browser.updateDeleteButton(UIImage(named: "assetName"))
```

You could also call it after a delay, but the above is cleaner IMO.

**Comment by klaus01** [comment]
very good, thanks
