### ISSUE TITLE
Update Swift

### ISSUE THREAD

**Issue by OscarGorog** [suzuki-0000/SKPhotoBrowser#324]
Please update to Swift 4.2

**Comment by happiehappie** [comment]
not sure if it's just me, but v6.0.0 gave me 
<img width="504" alt="screen shot 2018-09-18 at 4 05 31 pm" src="https://user-images.githubusercontent.com/6497131/45673233-bb62cd80-bb5c-11e8-8dc1-3d375ed852cb.png">
![Uploading Screen Shot 2018-09-18 at 4.05.37 PM.png…]()
