### ISSUE TITLE
Example is not build!

### ISSUE THREAD

**Issue by UzumakiAlfredo** [suzuki-0000/SKPhotoBrowser#365]
Hi, I just downloaded the example file but couldn't build & run it.

here are the Xcode the errors:
<img width="870" alt="Screen Shot 2019-04-07 at 9 39 55 AM" src="https://user-images.githubusercontent.com/29095193/55679052-6d0af580-5919-11e9-9bb8-42783ea898aa.png">

**Comment by PatrickDotStar** [comment]
Have you tried running `pod install` as the error suggests?

**Comment by UzumakiAlfredo** [comment]
Yea you are right! It just needed a pod update!
Thank You.
