### ISSUE TITLE
it is a bad experience

### ISSUE THREAD

**Issue by Jerryshen170918** [suzuki-0000/SKPhotoBrowser#376]
could you make this plug-in like wechat ->moments ? when i pull down ,the  photo become smaller,and end,photo disappear

**Comment by kaminwong** [comment]
This is not a bad experience, quite on the contrary, I think this library is quite awesome. Please fork and make your own adjustments, what you're requesting is not hard to implement, but frankly I don't see any marginal benefits in terms of user experience.
