### ISSUE TITLE
Save image without  Album permissions， it will crash

### ISSUE THREAD

**Issue by boboxiaodd** [suzuki-0000/SKPhotoBrowser#390]
if has permissions , it correct

**Comment by liseylee** [comment]
how to save image in this pod ?

**Comment by norman93sun** [comment]
+1

**Comment by tommyming** [comment]
@norman93sun @liseylee Sorry for the long-awaited update.
Tested on the main branch, can't find any crashes.

May I know the iOS version, Swift version, Library version? Thanks.

**Comment by norman93sun** [comment]
Here I found this crash only occur to iOS12 device.

Fixed by add `NSPhotoLibraryAddUsageDescription` to info.plist
