### ISSUE TITLE
trouble when rotating device

### ISSUE THREAD

**Issue by numfirst** [suzuki-0000/SKPhotoBrowser#4]
Hello! I have strange bug on my project and on your example. When rotating device image do not sizing on all screen.

**Comment by suzuki-0000** [comment]
Oh, I don't have checked it. I'll check and fix it.

**Comment by numfirst** [comment]
Thanks)

**Comment by pj4533** [comment]
:+1:    Having same issue, any rotation on image fails.

**Comment by suzuki-0000** [comment]
@numfirst  I found a bug for it, so updated. 
please check latest master or tag 1.1.0.

**Comment by pj4533** [comment]
I confirmed this is working better now.

2 Issues:

* Size of image seems wrong after rotation.  Maybe something with contentMode?  
* Dismissing view after rotation when using animatedFromView is unlikely to be correct.  With the rotation, the original view will have changed position.  Maybe just fade out on dismiss after rotation?

**Comment by suzuki-0000** [comment]
@pj4533, thanks for your confirmation.
> Size of image seems wrong after rotation. Maybe something with contentMode?
contentMode changed to center, It is likely to be a more improvement.
> Dismissing view after rotation when using animatedFromView is unlikely to be correct. 
oh, I'll consider it

**Comment by xiajinchun** [comment]
@pj4533 :+1:

**Comment by numfirst** [comment]
pj4533  :+1:

**Comment by numfirst** [comment]
Have any idea how to fix that?

**Comment by suzuki-0000** [comment]
this is working better now. but not for perfect..

**Comment by alexsanderskywork** [comment]
I try to fix it, but I could not to make it. I think there is a problem in tapView in SKZoomingScrollView
