### ISSUE TITLE
Mixed Language in SwiftPM

### ISSUE THREAD

**Issue by egesucu** [suzuki-0000/SKPhotoBrowser#415]
As of 7.0.0, SwiftPM package would not be built because of the usage of mixed-language.

### Possible Solution
As of Swift 5.3 SwiftPM supports mixed-language through separated targets. Example solution may be found [here](https://stackoverflow.com/questions/51540665/swift-package-manager-mixed-language-source-files).

**Comment by JohnGoodstadt** [comment]
This is also happening to me. If you have a solution please share it.

**Comment by egrimo** [comment]
> This is also happening to me. If you have a solution please share it.

The Solution lies on the Objc extension with UIImage+animatedGIF. Either, you need to separate OBJC source from Swift source, or you can convert the extension to Swift.

**Comment by egrimo** [comment]
Created https://github.com/suzuki-0000/SKPhotoBrowser/pull/422 for fixing the SwiftPM issue.
