### ISSUE TITLE
photoBrowser to present  will case the unvisible tabbar show.

### ISSUE THREAD

**Issue by qs991011** [suzuki-0000/SKPhotoBrowser#417]
in the delegate.  hidden the tabbar in willDismissAtPageIndex will nor working. and hidden tabbar in didDismissAtPageIndex it is normal. but the tabbar will flash . what can I do something to solove issue. 
and my xcode is 13.2.1, device is ios15.1. Thank you.

**Comment by 04192202** [comment]
I can have the same situation and click without any response

**Comment by tommyming** [comment]
Sorry for the late reply.
@04192202 @qs991011 May I know if this issue still exists in Xcode 15+ ? 
Thanks.

**Comment by tommyming** [comment]
Will close this issue for now, if issue still happens please open a new issue, thanks!
