### ISSUE TITLE
UI_USER_INTERFACE_IDIOM can't build in Xcode 13.3

### ISSUE THREAD

**Issue by lexin** [suzuki-0000/SKPhotoBrowser#420]
The error 
**_LLVM ERROR: out of memory_**
during making archive in Xcode 13.3
It seems that it is caused by UI_USER_INTERFACE_IDIOM. Need to use UIDevice.current.userInterfaceIdiom., probably.

**Comment by snazarovone** [comment]
hi, this is solution work for me

https://github.com/flutter/flutter/issues/100142#issuecomment-1072050199

**Comment by nguyenhuutinh** [comment]
hi, any update?

**Comment by tommyming** [comment]
Hello, may I know if this issue still exists on Xcode 15+? Thanks

**Comment by tommyming** [comment]
Will close this issue for now, if there are any updates, please feel free to open a new issue!
