### ISSUE TITLE
XCode Archive fails with abort trap 6

### ISSUE THREAD

**Issue by JohnGoodstadt** [suzuki-0000/SKPhotoBrowser#421]
An Intel Mac (2019) - Xcode 13.3 and a simple empty project with 1 pod installed 

`pod 'SKPhotoBrowser','~> 7.0'`

and 1 import statement

`import SKPhotoBrowser`

This runs on a simulator and on actual device iPhone 13 (iOS15.3.1) successfully. However, it fails on archiving with this error:

`Abort Trap 6`
`Uncategorized Command CompileSwiftSources failed with a nonzero exit code.`

I have already spent 2 days trying to sort this out so all my projects can be sent to the app store.

Thanks
John Goodstadt

![Screenshot 2022-03-23 at 09 50 03](https://user-images.githubusercontent.com/793166/159673207-749925c0-fd5a-4cb9-a239-922d4e1ef6b1.png)
![Screenshot 2022-03-23 at 09 59 39](https://user-images.githubusercontent.com/793166/159673356-37ee3090-0397-45f4-b6d4-e9e9ae15c443.png)

**Comment by huangfenfei** [comment]
me too!

**Comment by arianox** [comment]
I think this is already fixed with #419

**Comment by JohnGoodstadt** [comment]
Thanks, whilst this is true (I manually overwrote the change) it is not in version 7 - so my pod file line

`pod 'SKPhotoBrowser','~> 7.0'`

is not bringing it in.

I have tried Swift Package Manager but get a download error just like another issue in this list here.

Thanks
John Goodstadt

**Comment by haduong825** [comment]
I got the same issue.
<img width="947" alt="Screen Shot 2022-03-25 at 9 22 17 AM" src="https://user-images.githubusercontent.com/20613316/160041964-ed80be50-e132-4e59-a28c-65534501461c.png">

**Comment by chwahab** [comment]
For now modify your POD file

```pod 'SKPhotoBrowser', :git => 'https://github.com/suzuki-0000/SKPhotoBrowser.git', :branch => 'master'```

**Comment by tommyming** [comment]
Since there are no new updates on this issue, I am going to close this for now. If there are any problems, please feel free to create a new issue, thanks.
