### ISSUE TITLE
archive ipa error 

### ISSUE THREAD

**Issue by zhangcheng1989** [suzuki-0000/SKPhotoBrowser#438]
Undefined symbols for architecture arm64:
  "_swift_stdlib_isStackAllocationSafe", referenced from:
      _$ss10_NativeSetV11subtractingyAByxGqd__7ElementQyd__RszSTRd__lF14SKPhotoBrowser19SKZoomingScrollViewC_SayAIGTg5Tf4ng_n in libSKPhotoBrowser.a(SKPagingScrollView.o)
ld: symbol(s) not found for architecture arm64

**Comment by tommyming** [comment]
@zhangcheng1989 This should be an issue when you try to compile an x86-based code project on an M-series Mac, please check if the issue continues. Will close this issue for now.
