### ISSUE TITLE
Is this framework no longer maintenance?

### ISSUE THREAD

**Issue by alexanderkhitev** [suzuki-0000/SKPhotoBrowser#441]
Hey guys!

Is this framework no longer maintenance?

**Comment by tommyming** [comment]
@alexanderkhitev Hello, sorry for the late reply.
The original maintainer is busy these years due to personal issues. 

Currently, I will pick up this repository for now and review the PR and issues.
Please feel free to tag me if there are anything that needs me to investigate/review.
