### ISSUE TITLE
Why not add a thumbnail display

### ISSUE THREAD

**Issue by iPermanent** [suzuki-0000/SKPhotoBrowser#442]
I think thumbnail display is a very useful function, why not add this to the browser? Thanks

**Comment by tommyming** [comment]
@iPermanent Hello, sorry for the late reply. 

Would you like to describe more about "thumbnail display" ? Also, it would be nice if you are willing to create a PR, thanks.

**Comment by tommyming** [comment]
Will close this issue for now.
