### ISSUE TITLE
placeHolder  invalid

### ISSUE THREAD

**Issue by wujileii** [suzuki-0000/SKPhotoBrowser#444]
V  pod 'SKPhotoBrowser', '~> 7.1.0'
I use SKPhoto.photoWithImageURL(urlString, holder: UIImage(named: "placeHolder"))   He seems invalid
But  i use SKPhoto.photoWithImageURL(urlString), it's ok ,   it can't use placeHolder

**Comment by tommyming** [comment]
@wujileii Hello, as the issue is around 5 months old, I would close the issue for now. if the problem still exists, please feel free to open a new issue, I will have a check on that, thanks.
