### ISSUE TITLE
how to hide toolbar in version 7.0.0

### ISSUE THREAD

**Issue by huoda1237** [suzuki-0000/SKPhotoBrowser#445]
how to hide toolbar in version 7.0.0

**Comment by tommyming** [comment]
@huoda1237 Please check [SKPhotoBrowserOptions](https://github.com/suzuki-0000/SKPhotoBrowser/blob/master/SKPhotoBrowser/SKPhotoBrowserOptions.swift)

As components are independent, you may need to config it using multiple options.
