### ISSUE TITLE
is there a list of apps that use SKPhotoBrowser? 

### ISSUE THREAD

**Issue by alexanderkhitev** [suzuki-0000/SKPhotoBrowser#446]
Hello! Guys, is there a list of apps that use SKPhotoBrowser framework? If there is, please share it. Thanks.

**Comment by tommyming** [comment]
@alexanderkhitev Hello, sorry for the late reply. 

Currently, there is no list of apps for this repository, if you think it is nice to have it, please feel free to create a PR.

**Comment by alexanderkhitev** [comment]
Hey @tommyming ! No problem at all! I understand, thanks!
