### ISSUE TITLE
UIView+ScreenshotProtection.swift

### ISSUE THREAD

**Issue by jj2564** [suzuki-0000/SKPhotoBrowser#447]
This file did not use 
`import UIKit`
It cause compiler error.
With SPM I need to use last commit.

**Comment by tommyming** [comment]
@jj2564 Thanks for the report.

Seems you are using `branch` as the dependency rule. Change to `up to next minor version` should be able to fix the issue? I am not going to add a tag until I have extra time to perform code cleanup and write unit tests.

But if you are using the screenshot feature, will have a fix very soon.

**Comment by tommyming** [comment]
@jj2564 Maybe you can create a PR to add back the import? Thanks.
Since I am a collaborator, I cannot merge my own PR lol.

**Comment by jj2564** [comment]
Yes, I am using branch master for SPM.
I already create PR now!

**Comment by tommyming** [comment]
@jj2564 PR merged, please check if the things work properly, if not, please reopen this issue, thanks.
