### ISSUE TITLE
URL Pictures are not appearing in CollectionView

### ISSUE THREAD

**Issue by matheuztavarez** [suzuki-0000/SKPhotoBrowser#45]
Only the first picture is shown as someone clicked on it, but the collection view doesn't show all the pics on it, as it would do if the pics were stored locally (which worked fine, just when I changed to URL they don't appear anymore)

Im using a GET to get the URLs in an array, and then put them in the images array, with the caption and the URL for the picture, and then I set the delegate and data source to self, but they still don't appear.. :(

**Comment by suzuki-0000** [comment]
I don't get exactly what It happened, but something like this issue? https://github.com/suzuki-0000/SKPhotoBrowser/issues/1#issuecomment-155973007. 
or show example code makes me help)
