### ISSUE TITLE
privacy manifest

### ISSUE THREAD

**Issue by haoappwork** [suzuki-0000/SKPhotoBrowser#450]
Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file. Is there any plans to add a privacy manifest?

**Comment by tommyming** [comment]
Hello, thanks for opening the issue.

To be honest, there are no plans to add a privacy manifest since this library is a UI library, which is supposed to have no usage on the required reasons APIs.

But if you found any usage of required reason APIs, feel free to tell us and create a PR!

- Tommy
