### ISSUE TITLE
Migrate to SPM error: Could not find module 'SKPhotoBrowser' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by rbsolucoesemti** [suzuki-0000/SKPhotoBrowser#451]
Hello, I would like migrate from cocoapods to SPM but there is a error. 

Could not find module 'SKPhotoBrowser' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator.

Someone could help me with this ? 

Thanks.

**Comment by tommyming** [comment]
Hello.
This kind of error is mostly related to CPU architecture issue, is your project previously built on an Intel-based macbook, when using cocoapods?

There are various kinds of solutions from the community, please check stackflow about `Architectures` in .xcodeproj.

**Comment by tommyming** [comment]
@rbsolucoesemti May I know if the issue still exists? 
Since it is not really related to the repository itself, I may close the issue soon.

**Comment by tommyming** [comment]
Will close this issue for now, please feel free to reopen it if there are any new related problems appeared.
