### ISSUE TITLE
Crash on line 884

### ISSUE THREAD

**Issue by tooodooo** [suzuki-0000/SKPhotoBrowser#58]
If the image of collectionview item is not loaded, such as load failed or the web image does not exist, now touch the image that not loaded then close SKPhotoBrower, it will crash on line 884 of SKPhotoBrower.swift.

`fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by zxming** [comment]
You can change the code to 
`if scrollView.photo?.underlyingImage != nil {
            resizableImageView.image = scrollView.photo?.underlyingImage.rotateImageByOrientation()
        }`

**Comment by alexsanderkhitev** [comment]
It is fixed
