### ISSUE TITLE
Crashing when close view before image loaded 

### ISSUE THREAD

**Issue by ADevelopStudio** [suzuki-0000/SKPhotoBrowser#75]
if press close button before image was loaded - it leads to crash of the module.
simple solution is:
in file **SKPhotoBrowser.swift:**
public func performCloseAnimationWithScrollView(scrollView: SKZoomingScrollView) {

change :  
```
 resizableImageView.image = scrollView.photo?.underlyingImage.rotateImageByOrientation() ?? resizableImageView.image 
```
to:
```
        if scrollView.photo?.underlyingImage == nil {
            resizableImageView.image = UIImage()
        } else {
        resizableImageView.image = scrollView.photo?.underlyingImage.rotateImageByOrientation() ?? resizableImageView.image 
        }

```

**Comment by krummler** [comment]
Thanks for mentioning, I forgot to add this fix to the upstream earlier.

Fixed in commit 51bb8e4b5c647d611b49c730f193c1069a260704 and now merged to master.
