### ISSUE TITLE
Double tap to zoom doesn't always work

### ISSUE THREAD

**Issue by pj4533** [suzuki-0000/SKPhotoBrowser#8]
For the images I am using double-tap to zoom just moves the image down a bit, but doesn't zoom in.

I have seen it work in the example application, so I am not sure what is wrong.  I'll investigate more and followup here (will submit pull request if i find a solution).

**Comment by suzuki-0000** [comment]
:+1:

**Comment by pj4533** [comment]
@suzuki-0000 should be fixed with this pull request.
