### ISSUE TITLE
Is it possible to make new pod release?

### ISSUE THREAD

**Issue by barrault01** [suzuki-0000/SKPhotoBrowser#84]
Is it possible to make new pod release to reflect last changes? @krummler @alexsanderkhitev

**Comment by alexsanderkhitev** [comment]
@barrault01 Yes, it is

**Comment by alexsanderkhitev** [comment]
@barrault01 Please, you should update your pods and you get 1.8.2 version of SKPhotoBrowser.

**Comment by barrault01** [comment]
thanks :-)
