### ISSUE TITLE
Array cannot be bridged from Objective-C

### ISSUE THREAD

**Issue by ramesh-dev** [suzuki-0000/SKPhotoBrowser#89]
With Latest Version, when initializing SKPhotoBrowser using the init func 
`public convenience init(originImage: UIImage, photos: [SKPhotoProtocol], animatedFromView: UIView)`

am getting crash as **fatal error: array cannot be bridged from Objective-C**, please check 

currently the workaround posted in StackOverflow works,
[http://stackoverflow.com/questions/30100787/fatal-error-array-cannot-be-bridged-from-objective-c-why-are-you-even-trying](http://stackoverflow.com/questions/30100787/fatal-error-array-cannot-be-bridged-from-objective-c-why-are-you-even-trying)

**Comment by krummler** [comment]
I can't fix it now, but this problem happens pretty often with CoreData entities as well. Usually forcefully unwrapping the array works, something like 

    let unwrappedPhotos = photos.flatMap({ return $0 })

**Comment by barrault01** [comment]
@ramesh-dev declare the array you will pass  in the init as [SKPhotoProtocol] this should fix the problem.

**Comment by ramesh-dev** [comment]
sure, will try thanks!

**Comment by thefronter** [comment]
I have the same problem, and i dont know how i can fix it.
 This is my code:
```
func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
        let cell = collectionView.cellForItemAtIndexPath(indexPath) as! ImageCollectionViewCell
        if cell.imageView.image != nil {
            let originImage = cell.imageView.image
            var images = [SKPhoto]()
            let photo = SKPhoto.photoWithImage(originImage!)
            images.append(photo)
            let browser = SKPhotoBrowser(originImage: originImage!, photos: images, animatedFromView: cell)
            browser.initializePageIndex(indexPath.row)
            presentViewController(browser, animated: true, completion: {})
        }
    }
``` How I can fix it?

**Comment by barrault01** [comment]
Just change SKPhoto by SKPhotoProtocol in:
var images = [SKPhoto] ()
Le jeu. 21 avr. 2016 à 14:52, thefronter <notifications@github.com> a
écrit :
