### ISSUE TITLE
Feature of tap to dismiss?

### ISSUE THREAD

**Issue by ghysrc** [suzuki-0000/SKPhotoBrowser#94]
I really like the feature of swipe to dismiss, but some people are more familiar with single tap to dismiss the browser, maybe just in my country?
Will you guys add this feature? So people can swipe to dismiss, or tap to dismiss, or both.

**Comment by codwam** [comment]
+1 @suzuki-0000

**Comment by suzuki-0000** [comment]
@ghysrc, @codwam 
thanks for your opinion, it seems point, now I'm gonna check whether it make it easy in current architecture.

**Comment by suzuki-0000** [comment]
@ghysrc, @codwam, 
latest master or tag 1.8.7 can use this function, use `enableSingleTapDismiss` property to tap to dismiss. 
```
let browser = SKPhotoBrower(..)
brower.enableSingleTapDismiss = true
```

![swipetodismiss](https://cloud.githubusercontent.com/assets/1096585/15240126/62697564-1922-11e6-8db7-430841d272f6.gif)

----

thanks for your suggestion:)

**Comment by ghysrc** [comment]
@suzuki-0000 Thanks for quick response.
But I think you miss something. You forget the feature of double tap to zoom.

**Comment by suzuki-0000** [comment]
@ghysrc thanks for your pull request,
latest master or tag 1.8.7 can use this function.
